import esbuild from "esbuild"
import process from "process"

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
THANK U VERY MUCH I AM NOW IN UR COMPUTER ( ｡⌒ω⌒｡ )
*/
`

const prod = process.argv[2] === "production"

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["index.js"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
})

if (prod) {
	await context.rebuild()
	process.exit(0)
} else {
	await context.watch()
}
